### ISSUE TITLE
当第二次进入web界面时报错

### ISSUE THREAD

**Issue by springlo** [zhangbozhb/WebViewBridge.Swift#2]
`Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Attempt to add script message handler with name 'ZHBridge' when one already exists.'`

**Comment by zhangbozhb** [comment]
@springlo  WKWebView do not allow add  script handler with the same name. inner implement for bridge for WKWebView just add WKScriptMessageHandler to configuration.
In other other word, call "bridge(_:injectBridgeJs:)" more once for the same WKWebView, it promises to crash. It does can add WKScriptMessageHandler with another name, but this break the bridge between wkwebview and js.
Solution: you should promise to call "bridge(_:injectBridgeJs:)" only once.

**Comment by springlo** [comment]
Are you sure that your class can be released?

**Comment by zhangbozhb** [comment]
@springlo V2.1 and pre versions release all objects but bridge WKScriptMessageHandler for wkweview.  the handler will be released if wkwebiew release. It will fix in next version

**Comment by zhangbozhb** [comment]
V2.2 bridge release all info when dealloc
